[bumpver]
current_version = "0.1.0"
version_pattern = "MAJOR.MINOR.PATCH"
commit_message = "ðŸ”– bump version: {old_version} â†’ {new_version}"
tag_message = "v{new_version}"
tag_scope = "default"

[bumpver.file_patterns]
"pyproject.toml" = [
  "version = \"{version}\""
]
"src/__init__.py" = [
  "__version__ = \"{version}\""
]
"README.md" = [
  "CacheMaster v{version}"
]
